apiVersion: v1
kind: Pod
metadata:
  name: mysqldbinit
  labels:
    app: mysqldbinit
spec:
  containers:
  - name: mysqldbinit
    image: 328772008060.dkr.ecr.eu-central-1.amazonaws.com/init-repository:latest #gymnest-final-init:latest
    env:
      - name: SQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql.secret
            key: root_password
      - name: SQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql.secret
            key: sql_password
      - name: SQL_HOST
        valueFrom: 
          configMapKeyRef:
            name: django.config
            key: SQL_HOST
    
