pipeline {
    agent any

    environment {
        AWS_REGION = 'eu-central-1'
        EKS_CLUSTER = 'my-cluster'
        TAG = "latest"
        ACCOUNT_ID = '328772008060'
        ECR_REPO_DJANGO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/django-repository"
        ECR_REPO_INIT = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/init-repository"
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', credentialsId: 'github-credentials', url: 'https://github.com/faroukshtewee/DevOps-final.git'
            }
        }

        stage('Build Django Docker Image') {
            steps {
                bat 'docker build -t %ECR_REPO_DJANGO%:%TAG% ./GymNestProject'
            }
        }
        stage('Build Init Docker Image') {
            steps {
                bat 'docker build -t %ECR_REPO_INIT%:%TAG% ./init'
            }
        }
        stage('Push to ECR Django') {
            steps {
                bat """
                aws ecr get-login-password --region %AWS_REGION% | docker login --username AWS --password-stdin %ACCOUNT_ID%.dkr.ecr.%AWS_REGION%.amazonaws.com
                docker push %ECR_REPO_DJANGO%:%TAG%
                """
            }
        }
        stage('Push to ECR Init') {
            steps {
                bat """
                aws ecr get-login-password --region %AWS_REGION% | docker login --username AWS --password-stdin %ACCOUNT_ID%.dkr.ecr.%AWS_REGION%.amazonaws.com
                docker push %ECR_REPO_INIT%:%TAG%
                """
            }
        }

        stage('Deploy to EKS') {
            steps {
                bat """
                aws eks update-kubeconfig --name %EKS_CLUSTER% --region %AWS_REGION%

                kubectl get deployment django-app || kubectl create deployment django-app --image=%ECR_REPO_DJANGO%:%TAG%
                kubectl get deployment mysqldbinit || kubectl create deployment mysqldbinit --image=%ECR_REPO_INIT%:%TAG%

                kubectl set image deployment/django-app django-app=%ECR_REPO_DJANGO%:%TAG%
                kubectl set image deployment/mysqldbinit mysqldbinit=%ECR_REPO_INIT%:%TAG%
                """
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}